In [16]:
#Numpy and Array
#Numpy --> it is library in Python that provides support for the multi-dimensional arrays/matrices
import numpy as np

data = [1,2,3,4,5]

arr1 = np.array(data) #convert list 'data' into array

print(data)
print(arr1)
print(len(data))
print(arr1.shape)
print(type(arr1))

#List can hold different types of values, Array can hold only one type
lst = [1,2,3,4.5,5] #integer + float
arr2 = np.array(lst) #now the types of values of arr2 all changed to float
print(arr2)
print(arr1.dtype) 
print(arr2.dtype) # 2^64

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape)

arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr4)
print(arr4.shape)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
5
(5,)
<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5. ]
int64
float64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [19]:
#lists have a dynamic size; arrays have static size
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
a = np.identity(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
# 0 1 2 3 4 5...
a = np.arange(10) # for loop 이랑 똑같다 (range in for loop)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
a = np.arange(3,10,2)
a

array([3, 5, 7, 9])

In [31]:
#Array is just same as matrix
lst = [1,2,3]
lst2 = [4,5,6]

arr = np.array(lst) #[1,2,3]
arr2 = np.array(lst2) #[4,5,6]

print(lst+lst2)
print(arr+arr2) #[1+4,2+5,3+6]

#Matrix A : 2 x 3 ;;; Matrix B : 2 x 3 cannot multiply
#Matrix A : 3 x 4 ;;; Matrix B : 4 x 10 can multiply

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [41]:
#indexing in array is just same as list

lst = [1,2,3,4,5,6,7]
lst2 = [4,5,6,7,8]

arr = np.array(lst) #[1,2,3]
arr2 = np.array(lst2) #[4,5,6]

print(arr[0])
print(arr[0:4])

arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)
print(arr2[1][0])
print(arr2[1,0])
print(arr2[1,:]) #[5,6,7,8]
print(arr2[1, 1:]) #[6,7,8]

1
[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
5
5
[5 6 7 8]
[6 7 8]


In [42]:
names = np.array(["Scott","Alice","Kim","Lee"])
names

array(['Scott', 'Alice', 'Kim', 'Lee'], dtype='<U5')

In [43]:
# create an array with the random number in 0~1
data = np.random.rand(4,4)
data

array([[0.88136746, 0.42551163, 0.43808086, 0.10709863],
       [0.50683577, 0.31091327, 0.61815769, 0.77046725],
       [0.30062359, 0.14844856, 0.90457478, 0.61376849],
       [0.93053228, 0.77247188, 0.60982561, 0.16469546]])

In [50]:
data = np.random.randint(1,101, size = 10) #generate 10 integers between 1-100
print(data)
data2 = np.random.randint(1,101, size = (10,10)) #generate 10 by 10 integers between 1-100
print(data2)

[21 14 26 55 66 53 25 76 49 67]
[[74 40  2 96 21 26 24 30 59  8]
 [20 84 12  6 52  1 40 99 97 20]
 [11 13 47 55 37 18 77 71 28 58]
 [77 89 87 66 59 54 40 27 39 63]
 [99 17  7 79 82 57  4 20 67 29]
 [74 75 88 67 53 37 55 88  3 49]
 [15 13 86  5 50 34 72 99 16 29]
 [ 2 69 28 17 75 37 67 93  3 21]
 [36 71  7 60 64  2 19  3 95  5]
 [37 82 80 19 59  7 27 57 40 75]]


In [53]:
x = np.sum(data)
print(x)
y = np.sum(data2)
print(y)

452
4553


In [56]:
x = np.sum(data2, axis=1) #add every number in same row
print(x)
x = np.sum(data2, axis=0) #add every number in same column
print(x)

[380 431 415 601 461 589 419 412 362 483]
[445 553 444 470 552 273 425 587 447 357]


In [59]:
x = np.mean(data2) #get average
x

45.53

In [60]:
x = np.mean(data2, axis = 1) #calculate mean in every row
x

array([38. , 43.1, 41.5, 60.1, 46.1, 58.9, 41.9, 41.2, 36.2, 48.3])

In [62]:
x = np.max(data2) #Find the maximum number in array 'data2'
x

99

In [65]:
x = np.min(data2, axis = 0) #minimum in each column
x

array([ 2, 13,  2,  5, 21,  1,  4,  3,  3,  5])

In [67]:
x = np.argmax(data2) #find the index of maximum number in array 'data2'
x

17

In [70]:
lst = [3,4,5,2,1,6]
arr = np.array(lst)
print(arr)
arr = np.sort(arr) #sort in ascending order
print(arr)

[3 4 5 2 1 6]
[1 2 3 4 5 6]


In [71]:
shape_arr = arr.reshape((2,3))
shape_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
#Broadcasting --> Numpy allows arrays of different shapes to be used in mathematical operations
a = np.array([1,2,3,4,5]) * 2
# [1,2,3,4,5] * [2,
#                2,
#                2,
#                2,
#                2,]
a

array([ 2,  4,  6,  8, 10])

In [73]:
print(np.ones((3,4)) * np.arange(4))
# 1 1 1 1
# 1 1 1 1   x  [0,1,2,3]
# 1 1 1 1

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [75]:
# Install pandas
!pip install pandas

In [87]:
import pandas as pd
#Pandas provides new data structure other than list, array, set, dictionary, tuple

#Series -> Series is a 1d-array-like data structure provided by pandas library
#Dataframe -> Dataframe is a 2d-array-like data structure provided by pandas library

data = {
    "Name": ["Scott","Jason","Alice","Bob"],
    "Age": [17,18,18,16],
    "GPA": [3.4,3.2,4.0,2.7]
}
print(data)
print(data["Name"])
print(data["Name"][0])

#DataFrame
df = pd.DataFrame(data)
print(df)
print(type(df)) #type if DataFrame
print(df.info())
print(df["GPA"].mean())
print(round(df["GPA"].mean(),2))
print(df["GPA"].describe())
#std = standard deviation

{'Name': ['Scott', 'Jason', 'Alice', 'Bob'], 'Age': [17, 18, 18, 16], 'GPA': [3.4, 3.2, 4.0, 2.7]}
['Scott', 'Jason', 'Alice', 'Bob']
Scott
    Name  Age  GPA
0  Scott   17  3.4
1  Jason   18  3.2
2  Alice   18  4.0
3    Bob   16  2.7
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    4 non-null      object 
 1   Age     4 non-null      int64  
 2   GPA     4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes
None
3.325
3.32
count    4.000000
mean     3.325000
std      0.537742
min      2.700000
25%      3.075000
50%      3.300000
75%      3.550000
max      4.000000
Name: GPA, dtype: float64
